/**
 * Source of truth for resource icons.
 *
 * Add a new icon by adding one line here — no SVG content to paste:
 *   myicon: "./Resources/myicon.svg",
 *
 * Then run `npm run generate:icons` to regenerate
 * lib/renderer/resource-icons.ts from these files.
 */
export const ICON_MANIFEST: Record<string, string> = {
  aistudio: "./Resources/google-aistudio.svg",
  bash: "./Resources/bash.svg",
  blender: "./Resources/blender.svg",
  bun: "./Resources/bun.svg",
  chromium: "./Resources/chromium.svg",
  clang: "./Resources/c.svg",
  cloudflare: "./Resources/cloudflare-icon.svg",
  cmake: "./Resources/cmake.svg",
  cpp: "./Resources/c-plusplus.svg",
  csharp: "./Resources/c-sharp.svg",
  docker: "./Resources/docker.svg",
  electron: "./Resources/electron.svg",
  ffmpeg: "./Resources/ffmpeg-icon.svg",
  figma: "./Resources/figma.svg",
  gitlab: "./Resources/gitlab-icon.svg",
  golang: "./Resources/go.svg",
  gulp: "./Resources/gulp.svg",
  huggingface: "./Resources/hugging-face-icon.svg",
  java: "./Resources/java.svg",
  javascript: "./Resources/javascript.svg",
  kaggle: "./Resources/kaggle.svg",
  kotlin: "./Resources/kotlin-icon.svg",
  linux: "./Resources/linux.svg",
  love2d: "./Resources/love2d.svg",
  lua: "./Resources/lua.svg",
  luau: "./Resources/luau.svg",
  monogame: "./Resources/monogame.svg",
  netlify: "./Resources/netlify-icon.svg",
  nexcode: "./Resources/nexcode.svg",
  nextjs: "./Resources/nextjs-icon.svg",
  nodejs: "./Resources/nodejs-icon.svg",
  opengl: "./Resources/opengl.svg",
  pnpm: "./Resources/pnpm.svg",
  pypi: "./Resources/pypi.svg",
  python: "./Resources/python.svg",
  qt: "./Resources/qt.svg",
  react: "./Resources/react.svg",
  rlang: "./Resources/r-lang.svg",
  ruby: "./Resources/ruby.svg",
  rust: "./Resources/rust.svg",
  swift: "./Resources/swift.svg",
  tailwind: "./Resources/tailwindcss-icon.svg",
  tauri: "./Resources/tauri.svg",
  tensorflow: "./Resources/tensorflow.svg",
  typescript: "./Resources/typescript-icon.svg",
  v8: "./Resources/v8.svg",
  vite: "./Resources/vite-icon.svg",
  vue: "./Resources/vuejs.svg",
  wasm: "./Resources/wasm.svg",
  windows: "./Resources/microsoft-windows-icon.svg",
  yarn: "./Resources/yarn.svg",
  gitfork: "./Resources/git-fork.svg",
};